--------------------------------------------------------
--  File created - Wednesday-December-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ISPITI
--------------------------------------------------------

  CREATE TABLE "ANA"."ISPITI" 
   (	"IDISPITA" NUMBER(*,0), 
	"IDPREDMETA" NUMBER(*,0), 
	"MESTO" VARCHAR2(20 BYTE), 
	"DATUMIVREME" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KORISNICI
--------------------------------------------------------

  CREATE TABLE "ANA"."KORISNICI" 
   (	"BRINDEKSA" NUMBER(*,0), 
	"IME" VARCHAR2(20 BYTE), 
	"PREZIME" VARCHAR2(30 BYTE), 
	"KORSINICKOIME" VARCHAR2(20 BYTE), 
	"LOZINKA" VARCHAR2(20 BYTE), 
	"ADMIN" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREDMETI
--------------------------------------------------------

  CREATE TABLE "ANA"."PREDMETI" 
   (	"IDPREDMETA" NUMBER(*,0), 
	"NAZIVPREDMETA" VARCHAR2(30 BYTE), 
	"PROFESOR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRIJAVAISPITA
--------------------------------------------------------

  CREATE TABLE "ANA"."PRIJAVAISPITA" 
   (	"IDPRIJAVE" NUMBER(*,0), 
	"BRINDEKSA" NUMBER(*,0), 
	"IDISPITA" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ANA.ISPITI
SET DEFINE OFF;
REM INSERTING into ANA.KORISNICI
SET DEFINE OFF;
Insert into ANA.KORISNICI (BRINDEKSA,IME,PREZIME,KORSINICKOIME,LOZINKA,ADMIN) values (1,'Ana','Stevovic','anas','ana123',0);
Insert into ANA.KORISNICI (BRINDEKSA,IME,PREZIME,KORSINICKOIME,LOZINKA,ADMIN) values (2,'Milan','Pizurica','kimip','milanp',1);
Insert into ANA.KORISNICI (BRINDEKSA,IME,PREZIME,KORSINICKOIME,LOZINKA,ADMIN) values (3,'Kristina','Petrovic','kriskris','kristina0',0);
Insert into ANA.KORISNICI (BRINDEKSA,IME,PREZIME,KORSINICKOIME,LOZINKA,ADMIN) values (4,'Obrad','Masal','obrad1','obrad99',0);
REM INSERTING into ANA.PREDMETI
SET DEFINE OFF;
Insert into ANA.PREDMETI (IDPREDMETA,NAZIVPREDMETA,PROFESOR) values (1,'Engleski','P. Peric');
Insert into ANA.PREDMETI (IDPREDMETA,NAZIVPREDMETA,PROFESOR) values (2,'Matematika','D. Jokic');
Insert into ANA.PREDMETI (IDPREDMETA,NAZIVPREDMETA,PROFESOR) values (3,'Programiranje','K. Kuk');
Insert into ANA.PREDMETI (IDPREDMETA,NAZIVPREDMETA,PROFESOR) values (4,'Kriptologija','V. Minic');
REM INSERTING into ANA.PRIJAVAISPITA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ISPITI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANA"."ISPITI_PK" ON "ANA"."ISPITI" ("IDISPITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KORISNICI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANA"."KORISNICI_PK" ON "ANA"."KORISNICI" ("BRINDEKSA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PREDMETI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANA"."PREDMETI_PK" ON "ANA"."PREDMETI" ("IDPREDMETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIJAVAISPITA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANA"."PRIJAVAISPITA_PK" ON "ANA"."PRIJAVAISPITA" ("IDPRIJAVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ISPITI
--------------------------------------------------------

  ALTER TABLE "ANA"."ISPITI" ADD CONSTRAINT "ISPITI_PK" PRIMARY KEY ("IDISPITA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ANA"."ISPITI" MODIFY ("IDISPITA" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."ISPITI" MODIFY ("IDPREDMETA" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."ISPITI" MODIFY ("MESTO" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."ISPITI" MODIFY ("DATUMIVREME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KORISNICI
--------------------------------------------------------

  ALTER TABLE "ANA"."KORISNICI" ADD CONSTRAINT "KORISNICI_PK" PRIMARY KEY ("BRINDEKSA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ANA"."KORISNICI" MODIFY ("BRINDEKSA" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."KORISNICI" MODIFY ("IME" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."KORISNICI" MODIFY ("PREZIME" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."KORISNICI" MODIFY ("KORSINICKOIME" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."KORISNICI" MODIFY ("LOZINKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREDMETI
--------------------------------------------------------

  ALTER TABLE "ANA"."PREDMETI" ADD CONSTRAINT "PREDMETI_PK" PRIMARY KEY ("IDPREDMETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ANA"."PREDMETI" MODIFY ("IDPREDMETA" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."PREDMETI" MODIFY ("NAZIVPREDMETA" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."PREDMETI" MODIFY ("PROFESOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRIJAVAISPITA
--------------------------------------------------------

  ALTER TABLE "ANA"."PRIJAVAISPITA" ADD CONSTRAINT "PRIJAVAISPITA_PK" PRIMARY KEY ("IDPRIJAVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ANA"."PRIJAVAISPITA" MODIFY ("IDPRIJAVE" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."PRIJAVAISPITA" MODIFY ("BRINDEKSA" NOT NULL ENABLE);
 
  ALTER TABLE "ANA"."PRIJAVAISPITA" MODIFY ("IDISPITA" NOT NULL ENABLE);
